$(document).ready(function(){
    $(".navi>li>a").on("mouseenter",function(){
        $(".top").css({"background-color":"#fff"});
        $(".navi>li>a").css({"color":"#000"});
    });
    $(".top").on("mouseout",function(){
        $(".top").css({"background-color":"transparent"});
        $(".navi>li>a").css({"color":"#fff"});
    });
});